# Generated by Django 4.1.3 on 2022-11-22 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dieta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=2048)),
                ('carbohydrate', models.FloatField()),
                ('cholesterol', models.FloatField()),
                ('fiber', models.FloatField()),
                ('kilocalories', models.FloatField()),
                ('protein', models.FloatField()),
                ('sugar', models.FloatField()),
                ('monosaturated_fat', models.FloatField()),
                ('polysaturated_fat', models.FloatField()),
                ('saturated_fat', models.FloatField()),
                ('total_lipid', models.FloatField()),
                ('calcium', models.FloatField()),
                ('iron', models.FloatField()),
                ('sodium', models.FloatField()),
                ('vitamin_A_IU', models.FloatField()),
                ('vitamin_A_RAE', models.FloatField()),
                ('vitamin_B12', models.FloatField()),
                ('vitamin_B6', models.FloatField()),
                ('vitamin_C', models.FloatField()),
                ('vitamin_E', models.FloatField()),
                ('vitamin_K', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('price', models.FloatField()),
            ],
            options={
                'verbose_name_plural': 'Comidas',
            },
        ),
        migrations.CreateModel(
            name='Restricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comparacao', models.IntegerField(choices=[(0, 'MENOR'), (1, 'Menor ou igual'), (2, 'Igual'), (3, 'Maior ou igual'), (4, 'Maior')])),
                ('tipo', models.IntegerField(choices=[(0, 'Carboidratos'), (1, 'Colesterol'), (2, 'Fibras'), (3, 'Kilocalorias'), (4, 'Proteínas'), (5, 'Açúcares'), (6, 'Gordura monossaturada'), (7, 'Gordura polissaturada'), (8, 'Gordura saturada'), (9, 'Lipídios'), (10, 'Calcio'), (11, 'Ferro'), (12, 'Sódio'), (13, 'Vitamina A IU'), (14, 'Vitamina A RAE'), (15, 'Vitamina B12'), (16, 'Vitamina B6'), (17, 'Vitamina C'), (18, 'Vitamina E'), (19, 'Vitamina K')])),
                ('valor', models.FloatField(default=0)),
                ('dieta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.dieta')),
            ],
            options={
                'verbose_name': 'Restrição',
                'verbose_name_plural': 'Restrições',
            },
        ),
    ]
