# Generated by Django 4.1.3 on 2022-11-28 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_dieta_objetivo_dieta_variavel_alter_restricao_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='calcium',
        ),
        migrations.RemoveField(
            model_name='food',
            name='monosaturated_fat',
        ),
        migrations.RemoveField(
            model_name='food',
            name='polysaturated_fat',
        ),
        migrations.RemoveField(
            model_name='food',
            name='sugar',
        ),
        migrations.RemoveField(
            model_name='food',
            name='total_lipid',
        ),
        migrations.RemoveField(
            model_name='food',
            name='vitamin_A_IU',
        ),
        migrations.RemoveField(
            model_name='food',
            name='vitamin_A_RAE',
        ),
        migrations.RemoveField(
            model_name='food',
            name='vitamin_B12',
        ),
        migrations.RemoveField(
            model_name='food',
            name='vitamin_B6',
        ),
        migrations.RemoveField(
            model_name='food',
            name='vitamin_C',
        ),
        migrations.RemoveField(
            model_name='food',
            name='vitamin_E',
        ),
        migrations.RemoveField(
            model_name='food',
            name='vitamin_K',
        ),
    ]
